### ISSUE TITLE
Карта эмпатии

### ISSUE THREAD

**Issue by Ycalk** [Ycalk/DevOpsOdyssey#1]
Основное вопросы:
1) На кого направлена эмпатия?
2) Что им нужно сделать?
3) Что они слышат?
4) Что они делают? 
5) Что они видят?
6) Что они говорят?

7) Что они думают и чувствуют?

Пример карты:

![Image](https://user-images.githubusercontent.com/118367882/278050670-2c1c9db6-2876-46a3-9bf1-94674ae8b3de.jpg)

**Comment by Ycalk** [comment]
Постарайся выполнить быстрее - дедлайн просрочен. Если есть какие - то вопросы или проблемы пиши в лс

**Comment by HALOCHi** [comment]
![Image](https://github.com/Ycalk/DevOpsOdyssey/assets/86075962/caa90727-b81a-4e02-a216-56d75d274381)

**Comment by HALOCHi** [comment]
☺
