### ISSUE TITLE
Придумать мини-игры

### ISSUE THREAD

**Issue by Ycalk** [Ycalk/DevOpsOdyssey#10]
Игрок, по мере прохождения, будет участвовать в каких-то мини играх. Это может быть какой-то пазл или интересный диалог с персонажем с множеством развитий, **всего мини игр должно быть 5**. Так как у тебя, помимо роли геймдизайнера,  еще роль программиста делай в силу своих возможностей. Примеры мини игр:

1) Головоломка, где игрок должен найти и устранить баги в представленном коде (не самая лучшая идея, тк если игрок не знает языки программирования, или если мы представим код на яп который не знает игрок, то он не сможет пройти мини игру. Использовать если прямо вообще ничего не получается придумать)
2) Мини игра, где нужно собрать команду (идея классная, попробуй реализовать в формате дейтинга, по типу всяких баду дайвичи и подобного шлака)
3) Собрать пазл, представляющий сервер, чтобы восстановить его работоспособность. (не лучшая идея, но мейби если совсем ничего не получается придумать)
4) Игра, в которой игрок должен составить правильное описание процесса или продукта, используя предоставленные слова и фразы (в принципе нормальная идея)

Дедлайн среда

**Comment by optovolokn0** [comment]
**Структура мини-игр**

Кибербезопасность: на экране появляются вирусы, нужно успеть их "закликать" до того как они нанесут урон по инфраструктуре + не нажимать на безопасные клетки, победа зачтется при хп > 0%, время - 1,5-2 минуты?

Сисадмин: сборка пазла/пятнашек по починке сервера? либо та же игра 4 по описанию процесса/продукта

Фронтенд: мини-игра на выбор (палитра сайта, расположение элементов и т.д.), которые дают итоговый счет, счет выше определенного значения - победа?

Программист: какой-нибудь лабиринт? где ты двигаешься мимо багов, разрабатывая код /// игра на ввод слов на скорость, по типу слова-баги двигаются с экрана сверху вниз, и надо их написать [первое сделать проще]

Тим-лид: менеджер отношений между работниками ( скорее всего по типу есть имена/иконки на экране, появляются восклицательные знаки aka проблема, ты ее решаешь [тыкаешь на других работников, что-то даешь] )

**Comment by Ycalk** [comment]
Все мини игры классные, но для новой итерации сюжета нужно только 4 (кибербезопасность, фронтенд, программист, тим-лид)
