### ISSUE TITLE
Придумать связь между мини играми

### ISSUE THREAD

**Issue by Ycalk** [Ycalk/DevOpsOdyssey#11]
Проработать связь между мини играми. То есть это всякие диалоги мб активности и тп. **Напоминаю, длительность игры: хотя бы 10 минут**. Постарайся как-нибудь растянуть время

**Comment by optovolokn0** [comment]
**Структура мини-игр**

Кибербезопасность: на экране появляются вирусы, нужно успеть их "закликать" до того как они нанесут урон по инфраструктуре + не нажимать на безопасные клетки, победа зачтется при хп > 0%, время - 1,5-2 минуты?

Сисадмин: сборка пазла/пятнашек по починке сервера? либо та же игра 4 по описанию процесса/продукта

Фронтенд: мини-игра на выбор (палитра сайта, расположение элементов и т.д.), которые дают итоговый счет, счет выше определенного значения - победа?

Программист: какой-нибудь лабиринт? где ты двигаешься мимо багов, разрабатывая код /// игра на ввод слов на скорость, по типу слова-баги двигаются с экрана сверху вниз, и надо их написать [первое сделать проще]

Тим-лид: менеджер отношений между работниками ( скорее всего по типу есть имена/иконки на экране, появляются восклицательные знаки aka проблема, ты ее решаешь [тыкаешь на других работников, что-то даешь] ) 

**Фразы перед мини-играми**
(на выбор согласиться/вернуться позже)

Кибер: Последнее время мы стали свидетелями учащения кибератак на нашу сеть. Нам нужно найти способ защититься от этих угроз и усилить нашу безопасность. Готов помочь в этом?

Сис: У нас были несколько трудностей с нашим сервером в последние дни. Нам нужно обнаружить проблемы и решить их, чтобы предотвратить подобные инциденты в будущем. Поможешь мне?

Фронт: Для нового проекта нам нужно создать уникальный и легко воспринимаемый дизайн. Нам нужно привлечь пользователей своими идеями и концепциями. Готов принять вызов?

Прог: У нас есть несколько сложностей в коде, которые мешают прогрессу. Нам нужно найти правильный путь, чтобы все заработало как надо. Готов взяться за это?

Тим: У нас впереди новый проект и надо сплотить нашу команду. Нам предстоит балансировать работу и личные отношения работников, чтобы достичь успеха. Готов взяться за эту задачу?

**Переходы между мини-игр**

Разделение - победа/проигрыш

Кибер: Блестящая работа! Ваша способность быстро обнаруживать и устранять угрозы помогает нам сохранить нашу сеть в безопасности. / Иногда даже лучшие меры безопасности могут упустить что-то важное. Мы улучшим нашу защиту, чтобы гарантировать безопасность в будущем.

Сис: Отличная работа! Ваша способность оперативно реагировать на угрозы помогает нам сохранить наш сервер в безопасности. / Серверная работа - постоянный бой. Мы усилим наши меры, чтобы убедиться, что подобное больше не повторится

Фронт: Отлично справились! Ваша творческая визия помогает нам создавать уникальные и привлекательные продукты / Иногда идеи не срабатывают с первого раза, но ваше упорство поможет нам найти лучшее решение

Прог: Код успешно пройден! Ваше умение разбираться в сложностях кода дает нам надежду на быстрое завершение проекта / Не всегда все идет по плану, но это не конец. Мы сможем исправить ошибки и снова попытаемся

Тим: Отличная работа! Ваше умение эффективно управлять командой сделает наш проект еще более успешным / Не беспокойтесь, это всего лишь препятствие на нашем пути к успеху. Мы найдем другой способ добиться цели

**Comment by Ycalk** [comment]
Неплохо, может быть использовано в новой итерации сюжета
