### ISSUE TITLE
Переписать сюжет

### ISSUE THREAD

**Issue by Ycalk** [Ycalk/DevOpsOdyssey#15]
Во вкладке сюжет и персонажи представлен сюжет по главам. Там описана основная идея каждой главы, тебе нужно только написать что будут говорить персонажи друг другу. Если кажется, что что-то в сюжете не так или не логично - меняй на свое усмотрение

**Comment by Ycalk** [comment]
Тут начало сюжета (главы 1 и 2), постарайся оформить примерно в таком же стиле, чтобы получить фулл бал за артефакты геймдизайнера:

[Сюжет.docx](https://github.com/Ycalk/DevOpsOdyssey/files/13253007/default.docx)

**Comment by Ycalk** [comment]
Если будешь не успевать - пиши в лс, помогу, распределю задание на команду

**Comment by optovolokn0** [comment]
[scenario_fin.docx](https://github.com/Ycalk/DevOpsOdyssey/files/13327493/scenario_fin.docx)
