### ISSUE TITLE
Нарисовать локации для первых 2 глав сюжета

### ISSUE THREAD

**Issue by Ycalk** [Ycalk/DevOpsOdyssey#17]
Сюжет с первыми 2 главами:

https://github.com/Ycalk/DevOpsOdyssey/files/13253007/default.docx

Исходя из разговора героев и из описания глав (вкладка Сюжет и персонажи), постарайся нарисовать фон для первых 2 глав

**Comment by Trel11** [comment]
https://drive.google.com/drive/folders/1x-X10b56dFy-hWLAXYtsa3A-pTJhpD4x

**Comment by Ycalk** [comment]
👍
