### ISSUE TITLE
Дорисовать кабинеты сотрудников компании

### ISSUE THREAD

**Issue by Ycalk** [Ycalk/DevOpsOdyssey#18]
Нужно нарисовать кабинеты:
Томми Старка
Анастасии Сорью
Олега
Ивана Лейна

Также нужно нарисовать коридор по которому идут персонажи (Олег, виктор-95)

**Comment by Trel11** [comment]
1) есть
2) есть
3) пока нет
4) есть
5) коридор есть

**Comment by Ycalk** [comment]
👍
