### ISSUE TITLE
Написать вывод по аналитике

### ISSUE THREAD

**Issue by Ycalk** [Ycalk/DevOpsOdyssey#5]
В выводе более развернуто писать такую мысль:
О профессии девопс инженер мало кто знает, но хотят узнать больше именно поэтому мы делаем наш проект + какие-то свои мысли и наблюдения

**Comment by Ycalk** [comment]
Постарайся выполнить быстрее - дедлайн просрочен. Если есть какие - то вопросы или проблемы пиши в лс

**Comment by HALOCHi** [comment]
В ходе выявления целевой аудитории наша команда выяснила, что профессия DevOps-инженер малоизвестна, но аудитория желает знать больше о профессии нашего направления.
Также мы выяснили что конкретно требует аудитория от нашего будущего проекта:

1) Включить в игру образовательные элементы, объясняющие понятия и задачи DevOps

2) Использовать аниме-элементы для привлечения аудитории и увеличения интереса к игре

3) Создать оптимально дозированный игровой процесс, учитывая ограниченное время большинства игроков

**Comment by Ycalk** [comment]
Не совсем полный вывод, попробуй добавить больше своих мыслей

**Comment by Ycalk** [comment]
Все ок, но ты не написал кто целевая аудитория
