### ISSUE TITLE
Дописать завязку сюжета

### ISSUE THREAD

**Issue by Ycalk** [Ycalk/DevOpsOdyssey#9]
В "Сюжет и персонажи" есть прототип завязки, нужно дописать и, по своему усмотрению, что-то изменить.

**Comment by optovolokn0** [comment]
Открывающая сцена новеллы


Разговор Джозефа Джостера и Антона Стонковича в кабинете директора (Джозефа Джостера): 

Джозеф Джостер: Антон Стонкович, как Вы уже заметили, наша команда не успевает в дедлайны, необходимо с этим что-то делать. 
Антон Стонкович: Not stonks. 

В этот момент, внезапно поступает звонок Джозефу Джостеру. 

**Непонятный голос из трубки**
Джозеф Джостер: Да, Любочка ... угу ... угу ... зови его ко мне. 

**Дверь громко открывается**

Антон Стонкович, сидящий рядом, издаёт недовольный звук, напоминающий "Not stonks," и морщит лоб. Джозеф кладёт трубку на место и поворачивается к двери.

Джозеф Джостер: Здраво, мне тут передали, что вы ищете работу.

Олег: Да, все так.

Джозеф Джостер: Слушай, Олег, сейчас у нас сложная обстановка, нужно решать проблемы, если готов работать поставь подписи в договоре и поехали.

Олег: Будет ли какое-то собеседование? И можете, пожалуйста, рассказать о компании.

Антон Стонкович, нахмурившись, резко издает противный звук: "NOT TIME"

Джозеф Джостер: Ты его слышал, плохо нам, помощь нужна.

Олег: Это все очень....

Олега перебивает с хлопком открывшаяся дверь, и в кабинет брутально заходит Виктор-95

Виктор-95: Рад знакомству, парень. Мы здесь работаем как одна большая семья. Пойдем я тебе покажу все.

Олег: Но я ведь.....

Виктор-95, перебивая: На это нет времени.

--------

**Виктор-95 ведёт Олега по офису и показывает (кабинеты/рабочие места) каждого работника по порядку**

**1 - тимлид**
Виктор-95: Здесь работает тимлид. Он управляет нашей командой, общается с клиентами и поддерживает настрой команды.

**2 - спец по кибербезопасности**
Виктор-95: Это cybersecurity_name. Он защищает наши сети от цифровых атак, обеспечивает стабильную работу наших систем.

**3 - фронтенд**
Виктор-95: Дизайном наших продуктов занимается "frontend_name". Она создает пользовательский интерфейс.

**4 - сисадмин**
Виктор-95: Сисадмин в нашей команде работает над поддержкой сервера и помогает с проблемами с компьютерами.

**5 - лид программист**
Виктор-95; Последний работник - это я. Я пишу основной код для проектов, занимаюсь проектами и обучаю новичков.

Олег: Что именно мне нужно будет делать?

Виктор-95: Поспрашивай всех работников, узнай, какие у них проблемы и постарайся помочь им. Дерзай!

(переход на часть с мини-играми, всплывающее меню с выбором к кому пойти)

**Comment by Ycalk** [comment]
Есть некоторые доработки по сюжету. Смотри задание переписать сюжет - там все написано
